config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  scope :three_most_recent, -> { order(created_at: :desc).limit(3)}
  scope :most_reviews, -> {(
    select("products.id, products.name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(5)
    )}
  scope :locally_made, -> { where(country: "United States") }
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates_length_of :name, maximum: 40
  before_save(:titleize_product)

 private
   def titleize_product
     self.name = self.name.titleize
     self.country = self.country.titleize
   end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { less_than_or_equal_to: 5,  only_integer: true }
  validates_length_of :author, maximum: 40
  validates_length_of :content, minimum: 50
  validates_length_of :content, maximum: 250
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @products_most_reviews = Product.most_reviews
    @products_most_recent = Product.three_most_recent
    @products_locally_made = Product.locally_made
    render :index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit

  end

  def show
    @product = Product.find(params[:id])
    render :show
  end


  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :cost, :country)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully added!"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end
  # Other controller actions go here.

  private
  def review_params
    params.require(:review).permit(:author, :content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="center">
  <h1>Welcome to Mario's Specialty Foods!</h1>
  <h2>At Mario's you'll find top quality international food products at low prices!</h2>
  <h3>Check out some of our more popular products below!</h3>
</div>


<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <p class="products">Most Reviewed</p>
      <% if @products_most_reviews.any? %>
        <ul>
          <% @products_most_reviews.each do |most_reviewed| %>

            <li><%= link_to most_reviewed.name, product_path(most_reviewed) %></li>
          <% end %>
        </ul>
      <% else %>
        <p>There are no product reviews yet.</p>
      <% end %>
    </div>
    <div class="col-sm-4">
      <p class="products">Most Recently Added</p>
      <% if @products_most_recent.any? %>
        <ul>
          <% @products_most_recent.each do |most_recent| %>

            <li><%= link_to most_recent.name, product_path(most_recent) %></li>
          <% end %>
        </ul>
      <% else %>
        <p>There are no recent products added.</p>
      <% end %>
    </div>
    <div class="col-sm-4">
      <p class="products">Made In The USA</p>
      <% if @products_locally_made.any? %>
        <ul>
          <% @products_locally_made.each do |local_products| %>

            <li><%= link_to local_products.name, product_path(local_products) %></li>
          <% end %>
        </ul>
      <% else %>
        <p>There are currently no products made in the United States of America.</p>
      <% end %>
    </div>
  </div>
</div>

<p class="center"><%= link_to "Create new product", new_product_path %></p>
<p class="center"><%= link_to "View all current products", products_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product%>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost%>
  <%= f.label :country %>
  <%= f.text_field :country %>
  
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review%>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MariosFoodProducts</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Kalam&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Amarante&display=swap" rel="stylesheet">

</head>

<body>
  <%= flash[:alert] %>
  <%= flash[:notice] %>
  <%= yield %>
</body>
</html>

app/views/products/edit.html.erb
<div class="center">

  <h1>Edit product</h1>

  <%= render "layouts/product_form" %>
</div>

app/views/products/index.html.erb
<div class="center">

  <h1>Products</h1>

  <% if @products.any? %>
    <ul>
      <% @products.each do |product| %>

        <li><%= link_to product.name, product_path(product) %></li>
      <% end %>
    </ul>
  <% else %>
    <p>There are no products yet.</p>
  <% end %>

  <p><%= link_to "Create new product", new_product_path %></p>

  <p><%= link_to "Home", root_path %></p>

</div>

app/views/products/new.html.erb
<div class="center">

  <h1>New product</h1>

  <%= render "layouts/product_form" %>

</div>

app/views/products/show.html.erb
<div class="center">

  <h1>Product Name: <%= @product.name %></h1>
  <h3>Price: $<%= @product.cost %></h3>
  <h3>Made In: <%= @product.country %></h3>

  <% if @product.reviews.any? %>
    <h4>Here are the reviews for this product:</h4>

    <% @product.reviews.each do |review| %>
      <p><%= link_to review.author.to_str.titleize, product_review_path(@product, review) %></p>
    <% end %>
  <% else %>
    <p>No reviews are listed for this product.</p>
  <% end %>

  <p><%= link_to "Add a review", new_product_review_path(@product) %></p>

  <p><%= link_to "Edit", edit_product_path(@product) %></p>
  <p><%= link_to "Delete", product_path(@product),
                           :data => {:confirm => "You sure?",
                                     :method => "delete"} %></p>

  <p><%= link_to "Return to products", products_path %></p>

</div>

app/views/reviews/edit.html.erb
<div class="center">

  <h1>Edit review:</h1>

  <%= render "layouts/review_form" %>

</div>

app/views/reviews/new.html.erb
<div class="center">

  <h1>Add a new review:</h1>

  <%= render "layouts/review_form" %>

</div>

app/views/reviews/show.html.erb
<div class="center">


  <h1>Reviewer: <%= @review.author.to_str.titleize() %></h1>
  <img src="https://i.pravatar.cc/100" alt="fake avatar">
  <h2>Product: <%= @product.name %></h2>
  <h2>Rating: <%= @review.rating %></h2>

  <h3><%= @review.author.to_str.titleize() %> says: </h3>
  <h4>"<%= @review.content %>"</h4>

  <p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
  <p><%= link_to "Delete review", product_review_path(@product, @review),
                          :data => {:confirm => "Are you sure?",
                                         :method => "delete"} %></p>

  <p><%= link_to "Return to product", product_path(@product) %></p>


</div>